name: Build and test lab-cicd
push:
  branches:
    - main
jobs:
  test:
    runs-on: ubuntu-22.04
    name: Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test
